# Generated by Django 5.2 on 2025-05-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите заголовок статьи", max_length=100, verbose_name="Заголовок"),
                ),
                ("content", models.TextField(help_text="Основной текст статьи", verbose_name="Содержимое")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение-превью статьи (необязательно)",
                        null=True,
                        upload_to="blog/previews",
                        verbose_name="Превью",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_published", models.BooleanField(default=False, verbose_name="Опубликовано")),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество просмотров статьи (обновляется автоматически)",
                        verbose_name="Количество просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блоговая запись",
                "verbose_name_plural": "Блоговые записи",
                "ordering": ["title"],
            },
        ),
    ]
