# Generated by Django 5.2 on 2025-06-13 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title"],
                "permissions": [("can_manage_blog", "Может управлять публикациями в блоге")],
                "verbose_name": "Блоговая запись",
                "verbose_name_plural": "Блоговые записи",
            },
        ),
    ]
