# Generated by Django 5.2 on 2025-06-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category"],
                "permissions": [("can_unpublish_product", "Можете отменять публикацию продукта")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("published", "Опубликовано"), ("unpublished", "Снято с публикации")],
                default="draft",
                help_text="Выберите статус публикации",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
